name: Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup latex
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
      - name: Compile latex file
        run: |
          pdflatex test.tex
      - uses: actions/upload-artifact@v4
        with:
          name: test-pdf
          path: test.pdf


          